name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.1
      - name: Set up JDK 25
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'oracle'
          java-version: '25'
          cache: 'maven'
      - name: exercise01
        id: exercise01
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: exercise01
          setup-command: ''
          command: mvn -Dtest=TestAssignment#exercise01 test
          timeout: 10
          max-score: 10
      - name: exercise02
        id: exercise02
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: exercise02
          setup-command: ''
          command: mvn -Dtest=TestAssignment#exercise02 test
          timeout: 10
          max-score: 10
      - name: exercise03
        id: exercise03
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: exercise03
          setup-command: ''
          command: mvn -Dtest=TestAssignment#exercise03 test
          timeout: 10
          max-score: 10
      - name: exercise04
        id: exercise04
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: exercise04
          setup-command: ''
          command: mvn -Dtest=TestAssignment#exercise04 test
          timeout: 10
          max-score: 10
      - name: exercise05
        id: exercise05
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: exercise05
          setup-command: ''
          command: mvn -Dtest=TestAssignment#exercise05 test
          timeout: 10
          max-score: 10
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          exercise01_RESULTS: "${{steps.exercise01.outputs.result}}"
          exercise02_RESULTS: "${{steps.exercise02.outputs.result}}"
          exercise03_RESULTS: "${{steps.exercise03.outputs.result}}"
          exercise04_RESULTS: "${{steps.exercise04.outputs.result}}"
          exercise05_RESULTS: "${{steps.exercise05.outputs.result}}"
        with:
          runners: exercise01,exercise02,exercise03,exercise04,exercise05